# -*- coding: utf-8 -*-
# Genera write_psalm_widget.dart
# Actividad donde el estudiante escribe un salmo corto.
import os

output_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    'frontend', 'lib', 'widgets', 'write_psalm_widget.dart'
)

lines = []
def w(line=''):
    lines.append(line)

# --- IMPORTS ---
w("import 'package:flutter/material.dart';")
w("import 'package:google_fonts/google_fonts.dart';")
w()

# Inspiration data
w("const List<Map<String, String>> _inspirations = [")
for ref, txt in [
    ('Salmo 23:1', 'Jehov\u00e1 es mi pastor; nada me faltar\u00e1.'),
    ('Salmo 100:1-2', 'Cantad alegres a Dios, habitantes de toda la tierra. Servid a Jehov\u00e1 con alegr\u00eda.'),
    ('Salmo 46:10', 'Estad quietos, y conoced que yo soy Dios.'),
    ('Salmo 19:14', 'Sean gratos los dichos de mi boca y la meditaci\u00f3n de mi coraz\u00f3n delante de ti.'),
    ('Salmo 150:6', '\u00a1Todo lo que respira alabe a Jah! \u00a1Aleluya!'),
]:
    w(f"  {{'ref': '{ref}', 'text': '{txt}'}},")
w("];")
w()

# Tips
w("const List<String> _writingTips = [")
for tip in [
    'Comienza con una invocaci\u00f3n a Dios.',
    'Expresa un sentimiento genuino: gratitud, asombro, s\u00faplica.',
    'Usa im\u00e1genes de la naturaleza como met\u00e1foras.',
    'Incluye una declaraci\u00f3n de confianza en Dios.',
    'Termina con alabanza o esperanza.',
]:
    w(f"  '{tip}',")
w("];")
w()

# Widget
w(f"/// {'=' * 70}")
w(f"/// ESCRIBE TU SALMO {chr(8212)} ACTIVIDAD CREATIVA")
w(f"/// Instituto B{chr(237)}blico Elim Internacional")
w(f"/// {'=' * 70}")
w("class WritePsalmWidget extends StatefulWidget {")
w("  final bool isTeacher;")
w()
w("  const WritePsalmWidget({super.key, this.isTeacher = true});")
w()
w("  @override")
w("  State<WritePsalmWidget> createState() => _WritePsalmWidgetState();")
w("}")
w()

# STATE
w("class _WritePsalmWidgetState extends State<WritePsalmWidget>")
w("    with TickerProviderStateMixin {")
w("  int _page = 0; // 0=portada, 1=escribir, 2=preview")
w("  final _controller = TextEditingController();")
w("  String _psalmTitle = '';")
w("  int _currentInspiration = 0;")
w("  bool _submitted = false;")
w()
w("  late AnimationController _glowController;")
w("  late Animation<double> _glowAnimation;")
w("  late AnimationController _floatController;")
w("  late Animation<double> _floatAnimation;")
w()
w("  @override")
w("  void initState() {")
w("    super.initState();")
w("    _glowController = AnimationController(vsync: this, duration: const Duration(seconds: 2))..repeat(reverse: true);")
w("    _glowAnimation = Tween<double>(begin: 0.3, end: 1.0).animate(CurvedAnimation(parent: _glowController, curve: Curves.easeInOut));")
w("    _floatController = AnimationController(vsync: this, duration: const Duration(seconds: 3))..repeat(reverse: true);")
w("    _floatAnimation = Tween<double>(begin: -8, end: 8).animate(CurvedAnimation(parent: _floatController, curve: Curves.easeInOut));")
w("  }")
w()
w("  @override")
w("  void dispose() {")
w("    _controller.dispose();")
w("    _glowController.dispose();")
w("    _floatController.dispose();")
w("    super.dispose();")
w("  }")
w()

# BUILD
w("  @override")
w("  Widget build(BuildContext context) {")
w("    return Container(")
w("      decoration: const BoxDecoration(")
w("        gradient: LinearGradient(")
w("          begin: Alignment.topLeft, end: Alignment.bottomRight,")
w("          colors: [Color(0xFF0D1B2A), Color(0xFF1B2838), Color(0xFF162447)],")
w("        ),")
w("      ),")
w("      child: AnimatedSwitcher(")
w("        duration: const Duration(milliseconds: 500),")
w("        transitionBuilder: (child, anim) => FadeTransition(opacity: anim, child: child),")
w("        child: _page == 0 ? _buildCover() : _page == 1 ? _buildEditor() : _buildPreview(),")
w("      ),")
w("    );")
w("  }")
w()

# COVER PAGE
w("  Widget _buildCover() {")
w("    return Center(")
w("      key: const ValueKey('cover'),")
w("      child: SingleChildScrollView(")
w("        padding: const EdgeInsets.all(40),")
w("        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [")
w("          AnimatedBuilder(")
w("            animation: _glowAnimation,")
w("            builder: (context, child) {")
w("              return Container(")
w("                padding: const EdgeInsets.all(36),")
w("                decoration: BoxDecoration(")
w("                  shape: BoxShape.circle,")
w("                  gradient: RadialGradient(colors: [")
w("                    const Color(0xFFFFD54F).withValues(alpha: _glowAnimation.value * 0.4),")
w("                    Colors.transparent,")
w("                  ]),")
w("                  boxShadow: [BoxShadow(")
w("                    color: const Color(0xFFFFD54F).withValues(alpha: _glowAnimation.value * 0.3),")
w("                    blurRadius: 50, spreadRadius: 15,")
w("                  )],")
w("                ),")
w("                child: const Icon(Icons.edit_note_rounded, size: 100, color: Color(0xFFFFD54F)),")
w("              );")
w("            },")
w("          ),")
w("          const SizedBox(height: 40),")
w(f"          Text('ESCRIBE TU\\nSALMO', textAlign: TextAlign.center,")
w(f"            style: GoogleFonts.cinzel(fontSize: 68, fontWeight: FontWeight.w900,")
w(f"              color: const Color(0xFFFFD54F), letterSpacing: 4, height: 1.2,")
w(f"              shadows: [Shadow(color: Colors.black54, blurRadius: 20, offset: Offset(0, 4))])),")
w("          const SizedBox(height: 20),")
w(f"          Text('Actividad Creativa', style: GoogleFonts.lato(fontSize: 36, color: Colors.white70, fontWeight: FontWeight.w300, letterSpacing: 8)),")
w("          const SizedBox(height: 40),")
# Inspiration card
w("          Container(")
w("            padding: const EdgeInsets.all(30),")
w("            margin: const EdgeInsets.symmetric(horizontal: 20),")
w("            decoration: BoxDecoration(")
w("              gradient: LinearGradient(colors: [")
w("                const Color(0xFF1A237E).withValues(alpha: 0.5),")
w("                const Color(0xFF0D47A1).withValues(alpha: 0.3),")
w("              ]),")
w("              borderRadius: BorderRadius.circular(24),")
w("              border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.3), width: 2),")
w("            ),")
w("            child: Column(children: [")
w(f"              Text('{chr(171)}', style: GoogleFonts.cinzel(fontSize: 40, color: Color(0xFFFFD54F).withValues(alpha: 0.5))),")
w(f"              Text(_inspirations[_currentInspiration]['text']!, textAlign: TextAlign.center,")
w(f"                style: GoogleFonts.playfairDisplay(fontSize: 32, color: Colors.white, fontStyle: FontStyle.italic, height: 1.5)),")
w(f"              Text('{chr(187)}', style: GoogleFonts.cinzel(fontSize: 40, color: Color(0xFFFFD54F).withValues(alpha: 0.5))),")
w("              const SizedBox(height: 10),")
w("              Text(_inspirations[_currentInspiration]['ref']!,")
w("                style: GoogleFonts.cinzel(fontSize: 22, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("            ]),")
w("          ),")
w("          const SizedBox(height: 16),")
# Next inspiration
w("          TextButton.icon(")
w("            onPressed: () => setState(() => _currentInspiration = (_currentInspiration + 1) % _inspirations.length),")
w(f"            icon: const Icon(Icons.auto_awesome, color: Color(0xFFFFD54F), size: 24),")
w(f"            label: Text('Otra inspiraci{chr(243)}n', style: GoogleFonts.lato(fontSize: 22, color: Color(0xFFFFD54F))),")
w("          ),")
w("          const SizedBox(height: 30),")
# Instructions
w("          Container(")
w("            padding: const EdgeInsets.all(24),")
w("            margin: const EdgeInsets.symmetric(horizontal: 20),")
w("            decoration: BoxDecoration(")
w("              color: Colors.white.withValues(alpha: 0.05),")
w("              borderRadius: BorderRadius.circular(20),")
w("              border: Border.all(color: Colors.white24),")
w("            ),")
w("            child: Column(children: [")
w(f"              Text('INSTRUCCIONES', style: GoogleFonts.cinzel(fontSize: 30, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("              const SizedBox(height: 16),")
for idx, tip_text in enumerate([
    'Comienza con una invocaci\u00f3n a Dios',
    'Expresa un sentimiento genuino',
    'Usa im\u00e1genes de la naturaleza',
    'Incluye una declaraci\u00f3n de confianza',
    'Termina con alabanza o esperanza',
]):
    icons = ['Icons.record_voice_over', 'Icons.favorite', 'Icons.park', 'Icons.shield', 'Icons.celebration']
    w(f"              _buildTip({icons[idx]}, '{tip_text}'),")
    if idx < 4:
        w("              const SizedBox(height: 10),")
w("            ]),")
w("          ),")
w("          const SizedBox(height: 36),")
# Start button
w("          ElevatedButton.icon(")
w("            onPressed: () => setState(() => _page = 1),")
w("            icon: const Icon(Icons.create_rounded, size: 40),")
w(f"            label: Text('COMENZAR A ESCRIBIR', style: GoogleFonts.cinzel(fontSize: 30, fontWeight: FontWeight.bold)),")
w("            style: ElevatedButton.styleFrom(")
w("              backgroundColor: const Color(0xFFFFD54F),")
w("              foregroundColor: const Color(0xFF0D1B2A),")
w("              padding: const EdgeInsets.symmetric(horizontal: 50, vertical: 22),")
w("              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(30)),")
w("              elevation: 12,")
w("            ),")
w("          ),")
w("        ]),")
w("      ),")
w("    );")
w("  }")
w()

# Tip helper
w("  Widget _buildTip(IconData icon, String text) {")
w("    return Row(children: [")
w("      Icon(icon, color: Colors.white54, size: 28),")
w("      const SizedBox(width: 14),")
w("      Expanded(child: Text(text, style: GoogleFonts.lato(fontSize: 24, color: Colors.white70))),")
w("    ]);")
w("  }")
w()

# EDITOR PAGE
w("  Widget _buildEditor() {")
w("    return Center(")
w("      key: const ValueKey('editor'),")
w("      child: SingleChildScrollView(")
w("        padding: const EdgeInsets.all(40),")
w("        child: Column(children: [")
# Header
w("          Row(children: [")
w("            IconButton(onPressed: () => setState(() => _page = 0),")
w("              icon: const Icon(Icons.arrow_back_rounded, color: Colors.white54, size: 32)),")
w("            const SizedBox(width: 12),")
w(f"            Text('Escribe tu Salmo', style: GoogleFonts.cinzel(fontSize: 40, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("          ]),")
w("          const SizedBox(height: 10),")
w("          Divider(color: Colors.white24, thickness: 1),")
w("          const SizedBox(height: 24),")
# Title input
w(f"          Text('T{chr(237)}tulo de tu Salmo', style: GoogleFonts.lato(fontSize: 26, color: Colors.white70, fontWeight: FontWeight.w600)),")
w("          const SizedBox(height: 10),")
w("          TextField(")
w("            onChanged: (v) => setState(() => _psalmTitle = v),")
w("            style: GoogleFonts.cinzel(fontSize: 30, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold),")
w("            decoration: InputDecoration(")
w(f"              hintText: 'Ej: Salmo de gratitud',")
w("              hintStyle: GoogleFonts.cinzel(fontSize: 26, color: Colors.white24),")
w("              filled: true,")
w("              fillColor: Colors.white.withValues(alpha: 0.05),")
w("              border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: Color(0xFFFFD54F).withValues(alpha: 0.3))),")
w("              enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: Colors.white24)),")
w("              focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: Color(0xFFFFD54F), width: 2)),")
w("              contentPadding: const EdgeInsets.all(20),")
w("            ),")
w("          ),")
w("          const SizedBox(height: 24),")
# Body
w(f"          Text('Tu Salmo', style: GoogleFonts.lato(fontSize: 26, color: Colors.white70, fontWeight: FontWeight.w600)),")
w("          const SizedBox(height: 10),")
w("          TextField(")
w("            controller: _controller,")
w("            maxLines: 12,")
w("            style: GoogleFonts.playfairDisplay(fontSize: 26, color: Colors.white, height: 1.8),")
w("            decoration: InputDecoration(")
w(f"              hintText: 'Oh Se{chr(241)}or, mi Dios...\\n\\nEscribe tu salmo aqu{chr(237)}...',")
w("              hintStyle: GoogleFonts.playfairDisplay(fontSize: 24, color: Colors.white24, fontStyle: FontStyle.italic),")
w("              filled: true,")
w("              fillColor: Colors.white.withValues(alpha: 0.05),")
w("              border: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: Color(0xFFFFD54F).withValues(alpha: 0.3))),")
w("              enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: Colors.white24)),")
w("              focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(16), borderSide: BorderSide(color: Color(0xFFFFD54F), width: 2)),")
w("              contentPadding: const EdgeInsets.all(24),")
w("            ),")
w("          ),")
w("          const SizedBox(height: 16),")
# Char counter
w("          Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [")
w("            Text('${_controller.text.length} caracteres', style: GoogleFonts.lato(fontSize: 20, color: Colors.white38)),")
w("            AnimatedBuilder(animation: _floatAnimation, builder: (ctx, _) {")
w("              return Transform.translate(offset: Offset(0, _floatAnimation.value),")
w("                child: const Icon(Icons.auto_awesome, color: Color(0xFFFFD54F), size: 28));")
w("            }),")
w("          ]),")
w("          const SizedBox(height: 10),")
# Writing tips row
w("          Container(")
w("            padding: const EdgeInsets.all(16),")
w("            decoration: BoxDecoration(")
w("              color: const Color(0xFFFFD54F).withValues(alpha: 0.08),")
w("              borderRadius: BorderRadius.circular(16),")
w("              border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.2)),")
w("            ),")
w("            child: Row(children: [")
w("              const Icon(Icons.lightbulb_outline, color: Color(0xFFFFD54F), size: 28),")
w("              const SizedBox(width: 12),")
w("              Expanded(child: Text(_writingTips[_currentInspiration % _writingTips.length],")
w("                style: GoogleFonts.lato(fontSize: 22, color: Colors.white70, fontStyle: FontStyle.italic))),")
w("            ]),")
w("          ),")
w("          const SizedBox(height: 30),")
# Preview button
w("          Row(mainAxisAlignment: MainAxisAlignment.center, children: [")
w("            ElevatedButton.icon(")
w("              onPressed: _controller.text.trim().length >= 20 ? () => setState(() => _page = 2) : null,")
w("              icon: const Icon(Icons.visibility_rounded, size: 36),")
w(f"              label: Text('VISTA PREVIA', style: GoogleFonts.cinzel(fontSize: 28, fontWeight: FontWeight.bold)),")
w("              style: ElevatedButton.styleFrom(")
w("                backgroundColor: const Color(0xFFFFD54F),")
w("                foregroundColor: const Color(0xFF0D1B2A),")
w("                disabledBackgroundColor: Colors.white12,")
w("                disabledForegroundColor: Colors.white24,")
w("                padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 20),")
w("                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),")
w("                elevation: 8,")
w("              ),")
w("            ),")
w("          ]),")
w("          if (_controller.text.trim().length < 20)")
w(f"            Padding(padding: const EdgeInsets.only(top: 12),")
w(f"              child: Text('Escribe al menos 20 caracteres para continuar',")
w(f"                style: GoogleFonts.lato(fontSize: 18, color: Colors.white38))),")
w("        ]),")
w("      ),")
w("    );")
w("  }")
w()

# PREVIEW PAGE — beautiful pergamino
w("  Widget _buildPreview() {")
w("    return Center(")
w("      key: const ValueKey('preview'),")
w("      child: SingleChildScrollView(")
w("        padding: const EdgeInsets.all(40),")
w("        child: Column(children: [")
# Header
w("          Row(children: [")
w("            IconButton(onPressed: () => setState(() => _page = 1),")
w("              icon: const Icon(Icons.edit_rounded, color: Colors.white54, size: 32)),")
w("            const SizedBox(width: 12),")
w(f"            Text('Vista Previa', style: GoogleFonts.cinzel(fontSize: 36, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("          ]),")
w("          const SizedBox(height: 30),")
# Pergamino container
w("          Container(")
w("            width: double.infinity,")
w("            padding: const EdgeInsets.all(50),")
w("            decoration: BoxDecoration(")
w("              gradient: const LinearGradient(")
w("                begin: Alignment.topCenter, end: Alignment.bottomCenter,")
w("                colors: [Color(0xFF2C1810), Color(0xFF1A0F0A), Color(0xFF2C1810)],")
w("              ),")
w("              borderRadius: BorderRadius.circular(30),")
w("              border: Border.all(color: const Color(0xFFD4A574), width: 3),")
w("              boxShadow: [")
w("                BoxShadow(color: const Color(0xFFD4A574).withValues(alpha: 0.3), blurRadius: 30, spreadRadius: 5),")
w("                const BoxShadow(color: Colors.black45, blurRadius: 20, offset: Offset(0, 10)),")
w("              ],")
w("            ),")
w("            child: Column(children: [")
w("              const Icon(Icons.auto_awesome, color: Color(0xFFD4A574), size: 48),")
w("              const SizedBox(height: 16),")
# Title
w("              if (_psalmTitle.isNotEmpty)")
w("                Text(_psalmTitle.toUpperCase(), textAlign: TextAlign.center,")
w("                  style: GoogleFonts.cinzel(fontSize: 38, color: Color(0xFFD4A574), fontWeight: FontWeight.w900, letterSpacing: 4)),")
w("              if (_psalmTitle.isNotEmpty) const SizedBox(height: 8),")
w("              Container(width: 200, height: 2, color: const Color(0xFFD4A574).withValues(alpha: 0.5)),")
w("              const SizedBox(height: 24),")
# Body text
w("              Text(_controller.text, textAlign: TextAlign.center,")
w("                style: GoogleFonts.playfairDisplay(fontSize: 30, color: Color(0xFFE8D5B7), height: 1.8, fontStyle: FontStyle.italic)),")
w("              const SizedBox(height: 24),")
w("              Container(width: 200, height: 2, color: const Color(0xFFD4A574).withValues(alpha: 0.5)),")
w("              const SizedBox(height: 16),")
w(f"              Text('{chr(8212)} Estudiante del Instituto B{chr(237)}blico Elim {chr(8212)}',")
w(f"                style: GoogleFonts.lato(fontSize: 20, color: Color(0xFFD4A574).withValues(alpha: 0.7))),")
w("            ]),")
w("          ),")
w("          const SizedBox(height: 36),")
# Submit button
w("          if (!_submitted)")
w("            ElevatedButton.icon(")
w("              onPressed: () => setState(() => _submitted = true),")
w("              icon: const Icon(Icons.send_rounded, size: 36),")
w(f"              label: Text('ENVIAR MI SALMO', style: GoogleFonts.cinzel(fontSize: 28, fontWeight: FontWeight.bold)),")
w("              style: ElevatedButton.styleFrom(")
w("                backgroundColor: const Color(0xFF43A047),")
w("                foregroundColor: Colors.white,")
w("                padding: const EdgeInsets.symmetric(horizontal: 44, vertical: 20),")
w("                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),")
w("                elevation: 8,")
w("              ),")
w("            ),")
w("          if (_submitted)")
w("            Container(")
w("              padding: const EdgeInsets.all(24),")
w("              decoration: BoxDecoration(")
w("                color: const Color(0xFF43A047).withValues(alpha: 0.15),")
w("                borderRadius: BorderRadius.circular(20),")
w("                border: Border.all(color: const Color(0xFF43A047)),")
w("              ),")
w("              child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [")
w("                const Icon(Icons.check_circle, color: Color(0xFF43A047), size: 40),")
w("                const SizedBox(width: 16),")
w(f"                Text('{chr(161)}Salmo enviado exitosamente!',")
w(f"                  style: GoogleFonts.lato(fontSize: 28, color: Color(0xFF43A047), fontWeight: FontWeight.bold)),")
w("              ]),")
w("            ),")
w("          const SizedBox(height: 20),")
# Edit / Restart
w("          Row(mainAxisAlignment: MainAxisAlignment.center, children: [")
w("            TextButton.icon(")
w("              onPressed: () => setState(() => _page = 1),")
w("              icon: const Icon(Icons.edit, color: Colors.white54, size: 24),")
w(f"              label: Text('Editar', style: GoogleFonts.lato(fontSize: 22, color: Colors.white54)),")
w("            ),")
w("            const SizedBox(width: 20),")
w("            TextButton.icon(")
w("              onPressed: () => setState(() {")
w("                _page = 0; _controller.clear(); _psalmTitle = ''; _submitted = false;")
w("              }),")
w("              icon: const Icon(Icons.replay, color: Colors.white54, size: 24),")
w(f"              label: Text('Nuevo salmo', style: GoogleFonts.lato(fontSize: 22, color: Colors.white54)),")
w("            ),")
w("          ]),")
w("        ]),")
w("      ),")
w("    );")
w("  }")
w("}")

content = '\n'.join(lines) + '\n'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Generated: {output_path}')
print(f'Lines: {len(lines)}')
