# -*- coding: utf-8 -*-
# Genera proverbs_widget.dart
# Widget ultra-premium para Libro de Proverbios con 3D, efectos visuales y contenido interactivo.
import os

output_path = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    'frontend', 'lib', 'widgets', 'proverbs_widget.dart'
)

lines = []
def w(line=''):
    lines.append(line)

# --- IMPORTS ---
w("import 'dart:math';")
w("import 'package:flutter/material.dart';")
w("import 'package:google_fonts/google_fonts.dart';")
w()

# --- WIDGET ---
w("/// " + "=" * 70)
w("/// LIBRO DE PROVERBIOS " + chr(8212) + " WIDGET 3D INTERACTIVO ULTRA PREMIUM")
w("/// Instituto B" + chr(237) + "blico Elim Internacional")
w("/// " + "=" * 70)
w("class ProverbsWidget extends StatefulWidget {")
w("  const ProverbsWidget({super.key});")
w()
w("  @override")
w("  State<ProverbsWidget> createState() => _ProverbsWidgetState();")
w("}")
w()

# --- STATE ---
w("class _ProverbsWidgetState extends State<ProverbsWidget>")
w("    with TickerProviderStateMixin {")
w("  int _currentPage = 0;")
w()
w("  late AnimationController _glowController;")
w("  late Animation<double> _glowAnimation;")
w("  late AnimationController _floatController;")
w("  late Animation<double> _floatAnimation;")
w("  late AnimationController _rotateController;")
w("  late AnimationController _pulseController;")
w("  late Animation<double> _pulseAnimation;")
w()
w("  final int _totalPages = 7;")
w()
w("  @override")
w("  void initState() {")
w("    super.initState();")
w("    _glowController = AnimationController(vsync: this, duration: const Duration(seconds: 3))..repeat(reverse: true);")
w("    _glowAnimation = Tween<double>(begin: 0.3, end: 1.0).animate(CurvedAnimation(parent: _glowController, curve: Curves.easeInOut));")
w("    _floatController = AnimationController(vsync: this, duration: const Duration(seconds: 4))..repeat(reverse: true);")
w("    _floatAnimation = Tween<double>(begin: -10, end: 10).animate(CurvedAnimation(parent: _floatController, curve: Curves.easeInOut));")
w("    _rotateController = AnimationController(vsync: this, duration: const Duration(seconds: 20))..repeat();")
w("    _pulseController = AnimationController(vsync: this, duration: const Duration(seconds: 2))..repeat(reverse: true);")
w("    _pulseAnimation = Tween<double>(begin: 0.95, end: 1.05).animate(CurvedAnimation(parent: _pulseController, curve: Curves.easeInOut));")
w("  }")
w()
w("  @override")
w("  void dispose() {")
w("    _glowController.dispose();")
w("    _floatController.dispose();")
w("    _rotateController.dispose();")
w("    _pulseController.dispose();")
w("    super.dispose();")
w("  }")
w()

# BUILD
w("  @override")
w("  Widget build(BuildContext context) {")
w("    return Container(")
w("      decoration: const BoxDecoration(")
w("        gradient: LinearGradient(")
w("          begin: Alignment.topLeft, end: Alignment.bottomRight,")
w("          colors: [Color(0xFF1A0A2E), Color(0xFF16213E), Color(0xFF0F3460)],")
w("        ),")
w("      ),")
w("      child: Stack(children: [")
# Background particles
w("        ..._buildBackgroundParticles(),")
w("        Column(children: [")
# Navigation bar
w("          _buildNavBar(),")
# Content
w("          Expanded(")
w("            child: AnimatedSwitcher(")
w("              duration: const Duration(milliseconds: 600),")
w("              transitionBuilder: (child, anim) {")
w("                return FadeTransition(opacity: anim,")
w("                  child: SlideTransition(position: Tween<Offset>(begin: const Offset(0.05, 0), end: Offset.zero).animate(anim), child: child));")
w("              },")
w("              child: _buildPage(_currentPage),")
w("            ),")
w("          ),")
# Bottom nav
w("          _buildBottomNav(),")
w("        ]),")
w("      ]),")
w("    );")
w("  }")
w()

# Background particles
w("  List<Widget> _buildBackgroundParticles() {")
w("    return List.generate(12, (i) {")
w("      final rng = Random(i * 42);")
w("      return Positioned(")
w("        left: rng.nextDouble() * 1920,")
w("        top: rng.nextDouble() * 1080,")
w("        child: AnimatedBuilder(")
w("          animation: _glowAnimation,")
w("          builder: (_, __) => Opacity(")
w("            opacity: _glowAnimation.value * 0.15,")
w("            child: Container(")
w("              width: 4 + rng.nextDouble() * 6,")
w("              height: 4 + rng.nextDouble() * 6,")
w("              decoration: BoxDecoration(")
w("                shape: BoxShape.circle,")
w("                color: const Color(0xFFFFD54F),")
w("                boxShadow: [BoxShadow(color: const Color(0xFFFFD54F).withValues(alpha: 0.5), blurRadius: 10)],")
w("              ),")
w("            ),")
w("          ),")
w("        ),")
w("      );")
w("    });")
w("  }")
w()

# NAV BAR
w("  Widget _buildNavBar() {")
w("    return Container(")
w("      padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 16),")
w("      child: Row(children: [")
w("        const Icon(Icons.menu_book_rounded, color: Color(0xFFFFD54F), size: 36),")
w("        const SizedBox(width: 16),")
w("        Text('LIBRO DE PROVERBIOS', style: GoogleFonts.cinzel(fontSize: 28, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold, letterSpacing: 3)),")
w("        const Spacer(),")
# Page indicators
w("        ...List.generate(_totalPages, (i) => GestureDetector(")
w("          onTap: () => setState(() => _currentPage = i),")
w("          child: AnimatedContainer(")
w("            duration: const Duration(milliseconds: 300),")
w("            width: _currentPage == i ? 36 : 12, height: 12,")
w("            margin: const EdgeInsets.symmetric(horizontal: 4),")
w("            decoration: BoxDecoration(")
w("              borderRadius: BorderRadius.circular(6),")
w("              color: _currentPage == i ? const Color(0xFFFFD54F) : Colors.white24,")
w("            ),")
w("          ),")
w("        )),")
w("      ]),")
w("    );")
w("  }")
w()

# BOTTOM NAV
w("  Widget _buildBottomNav() {")
w("    return Container(")
w("      padding: const EdgeInsets.symmetric(horizontal: 40, vertical: 16),")
w("      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [")
w("        if (_currentPage > 0)")
w("          ElevatedButton.icon(")
w("            onPressed: () => setState(() => _currentPage--),")
w("            icon: const Icon(Icons.arrow_back_rounded, size: 28),")
w("            label: Text('ANTERIOR', style: GoogleFonts.lato(fontSize: 22, fontWeight: FontWeight.bold)),")
w("            style: ElevatedButton.styleFrom(")
w("              backgroundColor: Colors.white.withValues(alpha: 0.1),")
w("              foregroundColor: Colors.white70,")
w("              padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 14),")
w("              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),")
w("            ),")
w("          )")
w("        else const SizedBox.shrink(),")
w("        Text('${_currentPage + 1} / $_totalPages', style: GoogleFonts.orbitron(fontSize: 20, color: Colors.white38)),")
w("        if (_currentPage < _totalPages - 1)")
w("          ElevatedButton.icon(")
w("            onPressed: () => setState(() => _currentPage++),")
w("            icon: const Icon(Icons.arrow_forward_rounded, size: 28),")
w("            label: Text('SIGUIENTE', style: GoogleFonts.lato(fontSize: 22, fontWeight: FontWeight.bold)),")
w("            style: ElevatedButton.styleFrom(")
w("              backgroundColor: const Color(0xFFFFD54F),")
w("              foregroundColor: const Color(0xFF1A0A2E),")
w("              padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 14),")
w("              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),")
w("            ),")
w("          )")
w("        else const SizedBox.shrink(),")
w("      ]),")
w("    );")
w("  }")
w()

# PAGE ROUTER
w("  Widget _buildPage(int page) {")
w("    switch (page) {")
w("      case 0: return _buildPortada();")
w("      case 1: return _buildNombre();")
w("      case 2: return _buildAutor();")
w("      case 3: return _buildProposito();")
w("      case 4: return _buildEstructura();")
w("      case 5: return _buildTemas();")
w("      case 6: return _buildMujerVirtuosa();")
w("      default: return _buildPortada();")
w("    }")
w("  }")
w()

# ===================================================================
# PAGE 0: PORTADA
# ===================================================================
w("  Widget _buildPortada() {")
w("    return Center(")
w("      key: const ValueKey('p0'),")
w("      child: SingleChildScrollView(")
w("        padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("        child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [")
# 3D floating icon
w("          AnimatedBuilder(")
w("            animation: Listenable.merge([_glowAnimation, _floatAnimation]),")
w("            builder: (context, child) {")
w("              return Transform.translate(")
w("                offset: Offset(0, _floatAnimation.value),")
w("                child: Container(")
w("                  padding: const EdgeInsets.all(40),")
w("                  decoration: BoxDecoration(")
w("                    shape: BoxShape.circle,")
w("                    gradient: RadialGradient(colors: [")
w("                      const Color(0xFFFFD54F).withValues(alpha: _glowAnimation.value * 0.5),")
w("                      const Color(0xFFFF8F00).withValues(alpha: _glowAnimation.value * 0.2),")
w("                      Colors.transparent,")
w("                    ]),")
w("                    boxShadow: [")
w("                      BoxShadow(color: const Color(0xFFFFD54F).withValues(alpha: _glowAnimation.value * 0.4), blurRadius: 60, spreadRadius: 20),")
w("                      BoxShadow(color: const Color(0xFFFF8F00).withValues(alpha: _glowAnimation.value * 0.2), blurRadius: 100, spreadRadius: 40),")
w("                    ],")
w("                  ),")
w("                  child: const Icon(Icons.auto_stories_rounded, size: 120, color: Color(0xFFFFD54F)),")
w("                ),")
w("              );")
w("            },")
w("          ),")
w("          const SizedBox(height: 50),")
# Title
w("          Text('LIBRO DE\\nPROVERBIOS', textAlign: TextAlign.center,")
w("            style: GoogleFonts.cinzel(fontSize: 80, fontWeight: FontWeight.w900,")
w("              color: const Color(0xFFFFD54F), letterSpacing: 6, height: 1.15,")
w("              shadows: [")
w("                Shadow(color: Colors.black87, blurRadius: 30, offset: Offset(0, 6)),")
w("                Shadow(color: const Color(0xFFFF8F00).withValues(alpha: 0.5), blurRadius: 40),")
w("              ])),")
w("          const SizedBox(height: 30),")
# Subtitle line
w("          Container(width: 300, height: 3, decoration: BoxDecoration(")
w("            gradient: const LinearGradient(colors: [Colors.transparent, Color(0xFFFFD54F), Colors.transparent]),")
w("            borderRadius: BorderRadius.circular(2),")
w("          )),")
w("          const SizedBox(height: 24),")
# Keywords
w("          Wrap(spacing: 20, runSpacing: 14, alignment: WrapAlignment.center, children: [")
for kw in ['Sabidur\u00eda', 'Prudencia', 'Temor de Jehov\u00e1', 'Disciplina']:
    w(f"            _buildKeywordChip('{kw}'),")
w("          ]),")
w("          const SizedBox(height: 30),")
# Quote
w("          Container(")
w("            padding: const EdgeInsets.all(30),")
w("            decoration: BoxDecoration(")
w("              color: Colors.white.withValues(alpha: 0.04),")
w("              borderRadius: BorderRadius.circular(24),")
w("              border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.2), width: 2),")
w("            ),")
w("            child: Column(children: [")
w(f"              Text('{chr(171)}', style: GoogleFonts.cinzel(fontSize: 44, color: Color(0xFFFFD54F).withValues(alpha: 0.5))),")
w(f"              Text('El principio de la sabidur{chr(237)}a es el temor de Jehov{chr(225)}.',")
w(f"                textAlign: TextAlign.center,")
w(f"                style: GoogleFonts.playfairDisplay(fontSize: 42, color: Colors.white, fontStyle: FontStyle.italic, height: 1.5)),")
w(f"              Text('{chr(187)}', style: GoogleFonts.cinzel(fontSize: 44, color: Color(0xFFFFD54F).withValues(alpha: 0.5))),")
w("              const SizedBox(height: 10),")
w("              Text('Proverbios 1:7', style: GoogleFonts.cinzel(fontSize: 24, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("            ]),")
w("          ),")
w("        ]),")
w("      ),")
w("    );")
w("  }")
w()

# Keyword chip helper
w("  Widget _buildKeywordChip(String text) {")
w("    return AnimatedBuilder(")
w("      animation: _pulseAnimation,")
w("      builder: (_, __) => Transform.scale(")
w("        scale: _pulseAnimation.value,")
w("        child: Container(")
w("          padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 14),")
w("          decoration: BoxDecoration(")
w("            gradient: LinearGradient(colors: [")
w("              const Color(0xFFFFD54F).withValues(alpha: 0.25),")
w("              const Color(0xFFFF8F00).withValues(alpha: 0.15),")
w("            ]),")
w("            borderRadius: BorderRadius.circular(30),")
w("            border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.5), width: 2),")
w("            boxShadow: [BoxShadow(color: const Color(0xFFFFD54F).withValues(alpha: 0.15), blurRadius: 15)],")
w("          ),")
w("          child: Text(text, style: GoogleFonts.cinzel(fontSize: 24, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("        ),")
w("      ),")
w("    );")
w("  }")
w()

# ===================================================================
# PAGE 1: NOMBRE
# ===================================================================
w("  Widget _buildNombre() {")
w("    return SingleChildScrollView(")
w("      key: const ValueKey('p1'),")
w("      padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("        _buildSectionHeader('1', 'NOMBRE', Icons.translate_rounded),")
w("        const SizedBox(height: 30),")
# Hebrew card 3D
w("        Center(child: AnimatedBuilder(")
w("          animation: Listenable.merge([_glowAnimation, _floatAnimation]),")
w("          builder: (_, __) => Transform.translate(")
w("            offset: Offset(0, _floatAnimation.value * 0.5),")
w("            child: Container(")
w("              padding: const EdgeInsets.all(50),")
w("              decoration: BoxDecoration(")
w("                gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [")
w("                  const Color(0xFF1A237E).withValues(alpha: 0.7),")
w("                  const Color(0xFF0D47A1).withValues(alpha: 0.4),")
w("                ]),")
w("                borderRadius: BorderRadius.circular(30),")
w("                border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: _glowAnimation.value * 0.6), width: 3),")
w("                boxShadow: [")
w("                  BoxShadow(color: const Color(0xFF1A237E).withValues(alpha: 0.5), blurRadius: 40, spreadRadius: 5),")
w("                  BoxShadow(color: const Color(0xFFFFD54F).withValues(alpha: _glowAnimation.value * 0.15), blurRadius: 60, spreadRadius: 10),")
w("                ],")
w("              ),")
w("              child: Column(children: [")
w("                const Icon(Icons.history_edu_rounded, color: Color(0xFFFFD54F), size: 64),")
w("                const SizedBox(height: 20),")
# Hebrew word - HUGE
w(f"                Text('Mashal', style: GoogleFonts.cinzel(fontSize: 72, color: Color(0xFFFFD54F), fontWeight: FontWeight.w900, letterSpacing: 8)),")
w(f"                Text('{chr(1502)}{chr(1464)}{chr(1513)}{chr(1473)}{chr(1464)}{chr(1500)}', style: TextStyle(fontSize: 60, color: Colors.white54, fontFamily: 'serif')),")
w("                const SizedBox(height: 20),")
w("                Container(width: 200, height: 2, color: const Color(0xFFFFD54F).withValues(alpha: 0.5)),")
w("                const SizedBox(height: 20),")
w(f"                Text('= Comparaci{chr(243)}n o m{chr(225)}xima breve', style: GoogleFonts.lato(fontSize: 36, color: Colors.white, fontWeight: FontWeight.w500)),")
w("                const SizedBox(height: 16),")
w("                Container(")
w("                  padding: const EdgeInsets.symmetric(horizontal: 28, vertical: 12),")
w("                  decoration: BoxDecoration(")
w("                    color: const Color(0xFF43A047).withValues(alpha: 0.2),")
w("                    borderRadius: BorderRadius.circular(30),")
w("                    border: Border.all(color: const Color(0xFF43A047).withValues(alpha: 0.5)),")
w("                  ),")
w(f"                  child: Text('Libro sapiencial pr{chr(225)}ctico', style: GoogleFonts.lato(fontSize: 28, color: Color(0xFF43A047), fontWeight: FontWeight.bold)),")
w("                ),")
w("              ]),")
w("            ),")
w("          ),")
w("        )),")
w("        const SizedBox(height: 40),")
# Explanation cards
w("        _buildInfoCard(Icons.lightbulb_outline, 'Proverbio = ense" + chr(241) + "anza corta y memorable',")
w("          'Una frase pr" + chr(225) + "ctica que transmite sabidur" + chr(237) + "a divina para la vida cotidiana.', const Color(0xFFFFD54F)),")
w("        const SizedBox(height: 16),")
w("        _buildInfoCard(Icons.compare_arrows, 'Usa comparaciones',")
w("          'El perezoso vs. la hormiga, el sabio vs. el necio, etc.', const Color(0xFF1E88E5)),")
w("      ]),")
w("    );")
w("  }")
w()

# ===================================================================
# PAGE 2: AUTOR
# ===================================================================
w("  Widget _buildAutor() {")
w("    return SingleChildScrollView(")
w("      key: const ValueKey('p2'),")
w("      padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("        _buildSectionHeader('2', 'AUTOR PRINCIPAL', Icons.person_rounded),")
w("        const SizedBox(height: 30),")
# Solomon card - 3D
w("        Center(child: AnimatedBuilder(")
w("          animation: Listenable.merge([_glowAnimation, _floatAnimation]),")
w("          builder: (_, __) => Transform.translate(")
w("            offset: Offset(0, _floatAnimation.value * 0.5),")
w("            child: Container(")
w("              padding: const EdgeInsets.all(40),")
w("              decoration: BoxDecoration(")
w("                gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [")
w("                  const Color(0xFF4A148C).withValues(alpha: 0.6),")
w("                  const Color(0xFF7B1FA2).withValues(alpha: 0.3),")
w("                ]),")
w("                borderRadius: BorderRadius.circular(30),")
w("                border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.5), width: 3),")
w("                boxShadow: [BoxShadow(color: const Color(0xFF4A148C).withValues(alpha: 0.5), blurRadius: 40, spreadRadius: 5)],")
w("              ),")
w("              child: Column(children: [")
# Crown icon
w("                Stack(alignment: Alignment.center, children: [")
w("                  Container(width: 120, height: 120, decoration: BoxDecoration(")
w("                    shape: BoxShape.circle,")
w("                    gradient: RadialGradient(colors: [const Color(0xFFFFD54F).withValues(alpha: 0.3), Colors.transparent]),")
w("                  )),")
w("                  const Icon(Icons.diamond_rounded, color: Color(0xFFFFD54F), size: 80),")
w("                ]),")
w("                const SizedBox(height: 20),")
w(f"                Text('SALOM{chr(211)}N', style: GoogleFonts.cinzel(fontSize: 56, color: Color(0xFFFFD54F), fontWeight: FontWeight.w900, letterSpacing: 6)),")
w(f"                Text('Rey Sabio de Israel', style: GoogleFonts.lato(fontSize: 30, color: Colors.white70, fontWeight: FontWeight.w300, letterSpacing: 4)),")
w("                const SizedBox(height: 24),")
# Facts
w("                Wrap(spacing: 16, runSpacing: 12, alignment: WrapAlignment.center, children: [")
w(f"                  _buildFactChip(Icons.family_restroom, 'Hijo de David'),")
w(f"                  _buildFactChip(Icons.auto_awesome, 'Sabidur{chr(237)}a extraordinaria'),")
w(f"                  _buildFactChip(Icons.format_quote, '3,000 proverbios'),")
w("                ]),")
w("              ]),")
w("            ),")
w("          ),")
w("        )),")
w("        const SizedBox(height: 36),")
# Other authors
w(f"        Text('Tambi{chr(233)}n participaron:', style: GoogleFonts.cinzel(fontSize: 32, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("        const SizedBox(height: 20),")
for author_name, chapters, icon_name, desc, color_hex in [
    (f'Hombres de Ezequ{chr(237)}as', '25-29', 'Icons.groups_rounded', f'Copistas reales que recopilaron proverbios de Salom{chr(243)}n', '0xFF1E88E5'),
    ('Agur', '30', 'Icons.account_circle_rounded', f'Autor misterioso. Sus palabras contienen profunda humildad', '0xFF43A047'),
    ('Lemuel', '31', 'Icons.workspace_premium_rounded', f'Rey instruido por su madre. Describe a la mujer virtuosa', '0xFFE53935'),
]:
    w(f"        _buildAuthorCard('{author_name}', 'Cap. {chapters}', {icon_name}, '{desc}', Color({color_hex})),")
    w("        const SizedBox(height: 16),")
w("      ]),")
w("    );")
w("  }")
w()

# ===================================================================
# PAGE 3: PROPOSITO
# ===================================================================
w("  Widget _buildProposito() {")
w("    return SingleChildScrollView(")
w("      key: const ValueKey('p3'),")
w("      padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w(f"        _buildSectionHeader('3', 'PROP{chr(211)}SITO', Icons.track_changes_rounded),")
w("        const SizedBox(height: 30),")
# Biblical quote
w("        Center(child: Container(")
w("          padding: const EdgeInsets.all(40),")
w("          decoration: BoxDecoration(")
w("            gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [")
w("              const Color(0xFF1B5E20).withValues(alpha: 0.5),")
w("              const Color(0xFF2E7D32).withValues(alpha: 0.3),")
w("            ]),")
w("            borderRadius: BorderRadius.circular(30),")
w("            border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.4), width: 3),")
w("            boxShadow: [BoxShadow(color: const Color(0xFF1B5E20).withValues(alpha: 0.4), blurRadius: 40, spreadRadius: 5)],")
w("          ),")
w("          child: Column(children: [")
w("            const Icon(Icons.menu_book_rounded, color: Color(0xFFFFD54F), size: 56),")
w("            const SizedBox(height: 16),")
w("            Text('Proverbios 1:7', style: GoogleFonts.cinzel(fontSize: 30, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("            const SizedBox(height: 16),")
w(f"            Text('{chr(171)}', style: GoogleFonts.cinzel(fontSize: 44, color: Color(0xFFFFD54F).withValues(alpha: 0.5))),")
w(f"            Text('El principio de la sabidur{chr(237)}a\\nes el temor de Jehov{chr(225)}.',")
w(f"              textAlign: TextAlign.center,")
w(f"              style: GoogleFonts.playfairDisplay(fontSize: 48, color: Colors.white, fontStyle: FontStyle.italic, height: 1.5,")
w(f"                shadows: [Shadow(color: Colors.black54, blurRadius: 10)])),")
w(f"            Text('{chr(187)}', style: GoogleFonts.cinzel(fontSize: 44, color: Color(0xFFFFD54F).withValues(alpha: 0.5))),")
w("          ]),")
w("        )),")
w("        const SizedBox(height: 36),")
# Teachings grid
w(f"        Text('Ense{chr(241)}a:', style: GoogleFonts.cinzel(fontSize: 36, color: Color(0xFFFFD54F), fontWeight: FontWeight.bold)),")
w("        const SizedBox(height: 20),")
w("        Wrap(spacing: 20, runSpacing: 20, alignment: WrapAlignment.center, children: [")
for concept, icon_str, color_str in [
    ('Justicia', 'Icons.gavel_rounded', '0xFF1E88E5'),
    ('Juicio', 'Icons.balance_rounded', '0xFF7B1FA2'),
    ('Equidad', 'Icons.handshake_rounded', '0xFF43A047'),
    ('Prudencia', 'Icons.psychology_rounded', '0xFFFF8F00'),
]:
    w(f"          _buildConceptCard('{concept}', {icon_str}, Color({color_str})),")
w("        ]),")
w("      ]),")
w("    );")
w("  }")
w()

# ===================================================================
# PAGE 4: ESTRUCTURA
# ===================================================================
w("  Widget _buildEstructura() {")
w("    return SingleChildScrollView(")
w("      key: const ValueKey('p4'),")
w("      padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("        _buildSectionHeader('4', 'ESTRUCTURA', Icons.account_tree_rounded),")
w("        const SizedBox(height: 30),")
# Timeline-like structure
sections_data = [
    ('1-9', f'Discursos sobre la sabidur{chr(237)}a', 'Icons.school_rounded', '0xFF1E88E5',
     f'Instrucciones de un padre a su hijo. La sabidur{chr(237)}a personificada clama en las calles.'),
    ('10-22:16', 'Proverbios breves', 'Icons.format_list_bulleted_rounded', '0xFF43A047',
     f'Colecci{chr(243)}n principal de m{chr(225)}ximas cortas de Salom{chr(243)}n. Contrastes entre sabio y necio.'),
    (f'22:17{chr(8211)}24:34', 'Dichos de sabios', 'Icons.record_voice_over_rounded', '0xFF7B1FA2',
     f'Consejos de maestros sabios sobre temas pr{chr(225)}cticos de la vida diaria.'),
    (f'25{chr(8211)}29', f'Copiados por Ezequ{chr(237)}as', 'Icons.copy_rounded', '0xFFFF8F00',
     f'Proverbios de Salom{chr(243)}n recopilados por los hombres del rey Ezequ{chr(237)}as.'),
    (f'30{chr(8211)}31', 'Agur y Lemuel', 'Icons.auto_awesome_rounded', '0xFFE53935',
     f'Palabras de Agur (reflexiones) y de Lemuel (la mujer virtuosa, cap. 31).'),
]
for idx, (chaps, title, icon, color, desc) in enumerate(sections_data):
    w(f"        _buildStructureItem({idx}, '{chaps}', '{title}', {icon}, Color({color}), '{desc}'),")
    if idx < len(sections_data) - 1:
        w("        const SizedBox(height: 12),")
w("      ]),")
w("    );")
w("  }")
w()

# ===================================================================
# PAGE 5: TEMAS PRINCIPALES
# ===================================================================
w("  Widget _buildTemas() {")
w("    return SingleChildScrollView(")
w("      key: const ValueKey('p5'),")
w("      padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("        _buildSectionHeader('5', 'TEMAS PRINCIPALES', Icons.category_rounded),")
w("        const SizedBox(height: 30),")
# Theme cards in grid
themes_data = [
    ('La Lengua', '15:1', f'La blanda respuesta quita la ira; la palabra {chr(225)}spera hace subir el furor.', 'Icons.record_voice_over_rounded', '0xFF1E88E5'),
    ('Disciplina', '13:24', 'El que detiene el castigo, a su hijo aborrece.', 'Icons.school_rounded', '0xFFE53935'),
    ('Trabajo', '6:6', f'Ve a la hormiga, oh perezoso, mira sus caminos, y s{chr(233)} sabio.', 'Icons.work_rounded', '0xFF43A047'),
    ('Riqueza', '11:25', f'El alma generosa ser{chr(225)} prosperada.', 'Icons.account_balance_rounded', '0xFFFF8F00'),
    ('Matrimonio', '18:22', f'El que halla esposa halla el bien, y alcanza la benevolencia de Jehov{chr(225)}.', 'Icons.favorite_rounded', '0xFFE91E63'),
    ('Mujer virtuosa', f'31:10{chr(8211)}31', f'{chr(191)}Mujer virtuosa, qui{chr(233)}n la hallar{chr(225)}? Su estima sobrepasa a las piedras preciosas.', 'Icons.diamond_rounded', '0xFF7B1FA2'),
]
w("        Wrap(spacing: 20, runSpacing: 20, alignment: WrapAlignment.center, children: [")
for title, ref, verse, icon, color in themes_data:
    w(f"          _buildThemeCard('{title}', '{ref}', '{verse}', {icon}, Color({color})),")
w("        ]),")
w("      ]),")
w("    );")
w("  }")
w()

# ===================================================================
# PAGE 6: MUJER VIRTUOSA (special page)
# ===================================================================
w("  Widget _buildMujerVirtuosa() {")
w("    return SingleChildScrollView(")
w("      key: const ValueKey('p6'),")
w("      padding: const EdgeInsets.symmetric(horizontal: 60, vertical: 30),")
w("      child: Column(children: [")
w("        AnimatedBuilder(")
w("          animation: _glowAnimation,")
w("          builder: (_, __) => Container(")
w("            padding: const EdgeInsets.all(36),")
w("            decoration: BoxDecoration(")
w("              shape: BoxShape.circle,")
w("              gradient: RadialGradient(colors: [")
w("                const Color(0xFFE91E63).withValues(alpha: _glowAnimation.value * 0.4),")
w("                Colors.transparent,")
w("              ]),")
w("              boxShadow: [BoxShadow(color: const Color(0xFFE91E63).withValues(alpha: _glowAnimation.value * 0.3), blurRadius: 50, spreadRadius: 15)],")
w("            ),")
w("            child: const Icon(Icons.diamond_rounded, size: 90, color: Color(0xFFE91E63)),")
w("          ),")
w("        ),")
w("        const SizedBox(height: 30),")
w(f"        Text('LA MUJER VIRTUOSA', textAlign: TextAlign.center,")
w(f"          style: GoogleFonts.cinzel(fontSize: 56, fontWeight: FontWeight.w900, color: Color(0xFFE91E63), letterSpacing: 4)),")
w(f"        Text('Proverbios 31:10-31', style: GoogleFonts.cinzel(fontSize: 26, color: Colors.white54, fontWeight: FontWeight.w600)),")
w("        const SizedBox(height: 24),")
w("        Container(width: 250, height: 2, decoration: BoxDecoration(")
w("          gradient: const LinearGradient(colors: [Colors.transparent, Color(0xFFE91E63), Colors.transparent]),")
w("          borderRadius: BorderRadius.circular(2),")
w("        )),")
w("        const SizedBox(height: 30),")
# Verse
w("        Container(")
w("          padding: const EdgeInsets.all(36),")
w("          decoration: BoxDecoration(")
w("            gradient: LinearGradient(colors: [")
w("              const Color(0xFF880E4F).withValues(alpha: 0.4),")
w("              const Color(0xFFAD1457).withValues(alpha: 0.2),")
w("            ]),")
w("            borderRadius: BorderRadius.circular(24),")
w("            border: Border.all(color: const Color(0xFFE91E63).withValues(alpha: 0.4), width: 2),")
w("          ),")
w("          child: Column(children: [")
w(f"            Text('{chr(171)}', style: GoogleFonts.cinzel(fontSize: 40, color: Color(0xFFE91E63).withValues(alpha: 0.5))),")
w(f"            Text('{chr(191)}Mujer virtuosa, qui{chr(233)}n la hallar{chr(225)}?\\nSu estima sobrepasa largamente\\na las piedras preciosas.',")
w(f"              textAlign: TextAlign.center,")
w(f"              style: GoogleFonts.playfairDisplay(fontSize: 36, color: Colors.white, fontStyle: FontStyle.italic, height: 1.6)),")
w(f"            Text('{chr(187)}', style: GoogleFonts.cinzel(fontSize: 40, color: Color(0xFFE91E63).withValues(alpha: 0.5))),")
w("            const SizedBox(height: 10),")
w("            Text('Proverbios 31:10', style: GoogleFonts.cinzel(fontSize: 22, color: Color(0xFFE91E63), fontWeight: FontWeight.bold)),")
w("          ]),")
w("        ),")
w("        const SizedBox(height: 30),")
# Virtues
w("        Wrap(spacing: 16, runSpacing: 16, alignment: WrapAlignment.center, children: [")
virtues = [
    ('Trabaja con voluntad', 'Icons.volunteer_activism_rounded'),
    ('Provee para su casa', 'Icons.home_rounded'),
    (f'Se levanta de madrugad{chr(97)}', 'Icons.wb_sunny_rounded'),
    ('Tiende su mano al pobre', 'Icons.handshake_rounded'),
    (f'Se viste de fuerz{chr(97)}', 'Icons.shield_rounded'),
    (f'{chr(193)}bre su boca con sabidur{chr(237)}a', 'Icons.record_voice_over_rounded'),
]
for virtue, icon in virtues:
    w(f"          _buildVirtueChip('{virtue}', {icon}),")
w("        ]),")
w("        const SizedBox(height: 30),")
# Final declaration
w("        Container(")
w("          padding: const EdgeInsets.all(24),")
w("          decoration: BoxDecoration(")
w("            color: const Color(0xFFE91E63).withValues(alpha: 0.1),")
w("            borderRadius: BorderRadius.circular(20),")
w("            border: Border.all(color: const Color(0xFFE91E63).withValues(alpha: 0.3)),")
w("          ),")
w("          child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [")
w("            const Icon(Icons.star_rounded, color: Color(0xFFE91E63), size: 32),")
w("            const SizedBox(width: 16),")
w(f"            Text('Su valor sobrepasa a las piedras preciosas',")
w(f"              style: GoogleFonts.cinzel(fontSize: 24, color: Color(0xFFE91E63), fontWeight: FontWeight.bold)),")
w("            const SizedBox(width: 16),")
w("            const Icon(Icons.star_rounded, color: Color(0xFFE91E63), size: 32),")
w("          ]),")
w("        ),")
w("      ]),")
w("    );")
w("  }")
w()

# ===================================================================
# HELPER WIDGETS
# ===================================================================

# Section header
w("  Widget _buildSectionHeader(String number, String title, IconData icon) {")
w("    return Row(children: [")
w("      Container(")
w("        width: 60, height: 60,")
w("        decoration: BoxDecoration(")
w("          shape: BoxShape.circle,")
w("          gradient: const LinearGradient(colors: [Color(0xFFFFD54F), Color(0xFFFF8F00)]),")
w("          boxShadow: [BoxShadow(color: const Color(0xFFFFD54F).withValues(alpha: 0.4), blurRadius: 15)],")
w("        ),")
w("        child: Center(child: Text(number, style: GoogleFonts.orbitron(fontSize: 28, color: Color(0xFF1A0A2E), fontWeight: FontWeight.w900))),")
w("      ),")
w("      const SizedBox(width: 20),")
w("      Icon(icon, color: const Color(0xFFFFD54F), size: 40),")
w("      const SizedBox(width: 16),")
w("      Expanded(child: Text(title, style: GoogleFonts.cinzel(fontSize: 44, color: Color(0xFFFFD54F), fontWeight: FontWeight.w900, letterSpacing: 4))),")
w("    ]);")
w("  }")
w()

# Info card
w("  Widget _buildInfoCard(IconData icon, String title, String description, Color accent) {")
w("    return Container(")
w("      width: double.infinity,")
w("      padding: const EdgeInsets.all(24),")
w("      decoration: BoxDecoration(")
w("        color: accent.withValues(alpha: 0.08),")
w("        borderRadius: BorderRadius.circular(20),")
w("        border: Border.all(color: accent.withValues(alpha: 0.3)),")
w("      ),")
w("      child: Row(children: [")
w("        Icon(icon, color: accent, size: 40),")
w("        const SizedBox(width: 20),")
w("        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("          Text(title, style: GoogleFonts.cinzel(fontSize: 26, color: accent, fontWeight: FontWeight.bold)),")
w("          const SizedBox(height: 6),")
w("          Text(description, style: GoogleFonts.lato(fontSize: 22, color: Colors.white70)),")
w("        ])),")
w("      ]),")
w("    );")
w("  }")
w()

# Fact chip
w("  Widget _buildFactChip(IconData icon, String text) {")
w("    return Container(")
w("      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),")
w("      decoration: BoxDecoration(")
w("        color: const Color(0xFFFFD54F).withValues(alpha: 0.15),")
w("        borderRadius: BorderRadius.circular(30),")
w("        border: Border.all(color: const Color(0xFFFFD54F).withValues(alpha: 0.4)),")
w("      ),")
w("      child: Row(mainAxisSize: MainAxisSize.min, children: [")
w("        Icon(icon, color: const Color(0xFFFFD54F), size: 28),")
w("        const SizedBox(width: 10),")
w("        Text(text, style: GoogleFonts.lato(fontSize: 24, color: Colors.white, fontWeight: FontWeight.w600)),")
w("      ]),")
w("    );")
w("  }")
w()

# Author card
w("  Widget _buildAuthorCard(String name, String chapters, IconData icon, String desc, Color accent) {")
w("    return Container(")
w("      width: double.infinity,")
w("      padding: const EdgeInsets.all(24),")
w("      decoration: BoxDecoration(")
w("        gradient: LinearGradient(colors: [accent.withValues(alpha: 0.15), accent.withValues(alpha: 0.05)]),")
w("        borderRadius: BorderRadius.circular(20),")
w("        border: Border.all(color: accent.withValues(alpha: 0.4), width: 2),")
w("      ),")
w("      child: Row(children: [")
w("        Container(")
w("          width: 64, height: 64,")
w("          decoration: BoxDecoration(")
w("            shape: BoxShape.circle,")
w("            color: accent.withValues(alpha: 0.2),")
w("            border: Border.all(color: accent, width: 2),")
w("          ),")
w("          child: Icon(icon, color: accent, size: 36),")
w("        ),")
w("        const SizedBox(width: 20),")
w("        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("          Row(children: [")
w("            Text(name, style: GoogleFonts.cinzel(fontSize: 28, color: accent, fontWeight: FontWeight.bold)),")
w("            const SizedBox(width: 12),")
w("            Container(")
w("              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),")
w("              decoration: BoxDecoration(color: accent.withValues(alpha: 0.2), borderRadius: BorderRadius.circular(12)),")
w("              child: Text(chapters, style: GoogleFonts.orbitron(fontSize: 16, color: accent)),")
w("            ),")
w("          ]),")
w("          const SizedBox(height: 6),")
w("          Text(desc, style: GoogleFonts.lato(fontSize: 22, color: Colors.white70)),")
w("        ])),")
w("      ]),")
w("    );")
w("  }")
w()

# Concept card
w("  Widget _buildConceptCard(String title, IconData icon, Color accent) {")
w("    return AnimatedBuilder(")
w("      animation: _pulseAnimation,")
w("      builder: (_, __) => Transform.scale(")
w("        scale: _pulseAnimation.value,")
w("        child: Container(")
w("          width: 280, height: 180,")
w("          padding: const EdgeInsets.all(24),")
w("          decoration: BoxDecoration(")
w("            gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight,")
w("              colors: [accent.withValues(alpha: 0.3), accent.withValues(alpha: 0.1)]),")
w("            borderRadius: BorderRadius.circular(24),")
w("            border: Border.all(color: accent.withValues(alpha: 0.5), width: 2),")
w("            boxShadow: [BoxShadow(color: accent.withValues(alpha: 0.2), blurRadius: 20, spreadRadius: 2)],")
w("          ),")
w("          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [")
w("            Icon(icon, color: accent, size: 56),")
w("            const SizedBox(height: 12),")
w("            Text(title, style: GoogleFonts.cinzel(fontSize: 28, color: accent, fontWeight: FontWeight.bold)),")
w("          ]),")
w("        ),")
w("      ),")
w("    );")
w("  }")
w()

# Structure item
w("  Widget _buildStructureItem(int index, String chapters, String title, IconData icon, Color accent, String description) {")
w("    return Container(")
w("      width: double.infinity,")
w("      padding: const EdgeInsets.all(24),")
w("      decoration: BoxDecoration(")
w("        gradient: LinearGradient(colors: [accent.withValues(alpha: 0.15), accent.withValues(alpha: 0.05)]),")
w("        borderRadius: BorderRadius.circular(20),")
w("        border: Border.all(color: accent.withValues(alpha: 0.4), width: 2),")
w("      ),")
w("      child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [")
# Number badge
w("        Container(")
w("          width: 56, height: 56,")
w("          decoration: BoxDecoration(")
w("            shape: BoxShape.circle, color: accent.withValues(alpha: 0.2),")
w("            border: Border.all(color: accent, width: 2),")
w("          ),")
w("          child: Icon(icon, color: accent, size: 30),")
w("        ),")
w("        const SizedBox(width: 20),")
w("        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("          Row(children: [")
w("            Container(")
w("              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),")
w("              decoration: BoxDecoration(color: accent.withValues(alpha: 0.25), borderRadius: BorderRadius.circular(12)),")
w("              child: Text(chapters, style: GoogleFonts.orbitron(fontSize: 18, color: accent, fontWeight: FontWeight.bold)),")
w("            ),")
w("            const SizedBox(width: 16),")
w("            Expanded(child: Text(title, style: GoogleFonts.cinzel(fontSize: 26, color: accent, fontWeight: FontWeight.bold))),")
w("          ]),")
w("          const SizedBox(height: 8),")
w("          Text(description, style: GoogleFonts.lato(fontSize: 22, color: Colors.white70, height: 1.4)),")
w("        ])),")
# Connector line
w("        if (index < 4)")
w("          Container(width: 3, height: 60, margin: const EdgeInsets.only(left: 8), color: accent.withValues(alpha: 0.3)),")
w("      ]),")
w("    );")
w("  }")
w()

# Theme card
w("  Widget _buildThemeCard(String title, String reference, String verse, IconData icon, Color accent) {")
w("    return Container(")
w("      width: 380, ")
w("      padding: const EdgeInsets.all(24),")
w("      decoration: BoxDecoration(")
w("        gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight,")
w("          colors: [accent.withValues(alpha: 0.2), accent.withValues(alpha: 0.08)]),")
w("        borderRadius: BorderRadius.circular(24),")
w("        border: Border.all(color: accent.withValues(alpha: 0.4), width: 2),")
w("        boxShadow: [BoxShadow(color: accent.withValues(alpha: 0.15), blurRadius: 20)],")
w("      ),")
w("      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [")
w("        Row(children: [")
w("          Icon(icon, color: accent, size: 36),")
w("          const SizedBox(width: 12),")
w("          Expanded(child: Text(title, style: GoogleFonts.cinzel(fontSize: 26, color: accent, fontWeight: FontWeight.bold))),")
w("        ]),")
w("        const SizedBox(height: 8),")
w("        Container(")
w("          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),")
w("          decoration: BoxDecoration(color: accent.withValues(alpha: 0.15), borderRadius: BorderRadius.circular(12)),")
w("          child: Text(reference, style: GoogleFonts.orbitron(fontSize: 16, color: accent)),")
w("        ),")
w("        const SizedBox(height: 12),")
w(f"        Text('{chr(171)}$verse{chr(187)}', style: GoogleFonts.playfairDisplay(fontSize: 20, color: Colors.white70, fontStyle: FontStyle.italic, height: 1.5)),")
w("      ]),")
w("    );")
w("  }")
w()

# Virtue chip
w("  Widget _buildVirtueChip(String text, IconData icon) {")
w("    return Container(")
w("      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),")
w("      decoration: BoxDecoration(")
w("        color: const Color(0xFFE91E63).withValues(alpha: 0.15),")
w("        borderRadius: BorderRadius.circular(30),")
w("        border: Border.all(color: const Color(0xFFE91E63).withValues(alpha: 0.4)),")
w("      ),")
w("      child: Row(mainAxisSize: MainAxisSize.min, children: [")
w("        Icon(icon, color: const Color(0xFFE91E63), size: 26),")
w("        const SizedBox(width: 10),")
w("        Text(text, style: GoogleFonts.lato(fontSize: 22, color: Colors.white, fontWeight: FontWeight.w600)),")
w("      ]),")
w("    );")
w("  }")
w("}")

content = '\n'.join(lines) + '\n'
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Generated: {output_path}')
print(f'Lines: {len(lines)}')
